# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
import numpy as np
print(np.version)
print(np.show_config())

<module 'numpy.version' from '/usr/local/lib/python3.7/dist-packages/numpy/version.py'>
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SI

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
import numpy as np
res=np.zeros(10)

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
import numpy as np
x=np.array([[ 0, 2],
           [2, 4]])

#Method - 1
Size=x.size
Itemsize=x.itemsize
Memory_Size=Size*Itemsize
print(Memory_Size)

#Method-2
print(x.nbytes)

32
32


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
import numpy as np

res=np.info(np.add)

print(res)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
import numpy as np

arr=np.zeros(10, dtype="int")

arr[4]=1

print(arr)

[0 0 0 0 1 0 0 0 0 0]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
import numpy as np

vec=np.arange(10,50)

print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5])

res=arr[::-1]

print(arr)

print(res)

[1 2 3 4 5]
[5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
import numpy as np

mat=np.arange(0,9).reshape(3,3)

print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
import numpy as np

arr=np.array([1,2,0,4,4,5])

ind=np.nonzero(arr)

print(*ind)


[0 1 3 4 5]


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
import numpy as np

mat=np.eye(3,3,dtype="int")

print(mat)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
import numpy as np

arr=np.random.rand(3,3,3)

print(arr)

[[[0.73021209 0.57602703 0.73923231]
  [0.68633384 0.89218839 0.31167609]
  [0.76426122 0.02387797 0.76333855]]

 [[0.68977039 0.28598102 0.01124972]
  [0.29400483 0.36761271 0.13158351]
  [0.00841154 0.23705981 0.70603546]]

 [[0.55576391 0.60232078 0.60783531]
  [0.87959739 0.73019613 0.10514591]
  [0.84521828 0.29311009 0.31620987]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
import numpy as np

arr=np.random.randint(1,50,(10,10))
    
mi=np.min(arr)

ma=np.max(arr)

print(arr)

print(mi)

print(ma)


[[23 32 31 44 30 42  9 41  4 38]
 [11 11 22 48 10  5 46 21 19 26]
 [46 38 26 14 24 10 40 28 15 41]
 [43  3  2 45 18 47 14 44 47 37]
 [27 16 25 45 16 31 34 36 49 22]
 [38 49 17  9 35 15 21 27 43 40]
 [14 25 41  5  9 49 28 25  1 24]
 [46 31 15 46 21 49 11 22 19 46]
 [12 45 24 37 49 27  3 24 47 45]
 [44 32 30  5  1 36  8 23 17  2]]
1
49


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
import numpy as np

arr=np.random.random(30)

val=np.mean(arr)

res=round(val,2)

print(arr)

print(res)

[0.66413537 0.1600426  0.96617233 0.50793873 0.75909653 0.42561
 0.30959332 0.72097504 0.01249534 0.74916862 0.35491843 0.66475209
 0.89140246 0.71709102 0.76633085 0.76594753 0.52666353 0.51911649
 0.00386852 0.3672765  0.24604975 0.33787482 0.22491318 0.0541659
 0.60146636 0.14856419 0.3864515  0.88919754 0.11088511 0.51236601]
0.48


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
import numpy as np

arr=np.ones((4,4),dtype="int64")

arr[1:-1,1:-1]=0

res_arr=arr

print(res_arr)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
import numpy as np

arr=np.array([[9,9,9],[9,9,9]])

border_arr=np.pad(arr,pad_width=1,mode="constant",constant_values=0)

print(arr)

print(border_arr)

[[9 9 9]
 [9 9 9]]
[[0 0 0 0 0]
 [0 9 9 9 0]
 [0 9 9 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
import numpy as np

res = np.diag(1+np.arange(4), k = -1)

print (res)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
import numpy as np

res = np.zeros ((8,8), dtype=int)
res[1::2, ::2]= 1
res[::2, 1::2] = 1

print (res)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
import numpy as np

res=np.unravel_index(100, (6,7,8))

print (res)

(1, 5, 4)


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
import numpy as np

arr=np.random.random((5,5))

print(arr)

arr_max,arr_min=arr.max(),arr.min()

norm_arr=(arr-arr_min)/(arr_max-arr_min)

print(norm_arr)

[[0.91171514 0.85834394 0.4708431  0.71965181 0.39778082]
 [0.77727255 0.70012195 0.41844366 0.75916009 0.33330657]
 [0.36203142 0.4722163  0.39895464 0.36883909 0.70680613]
 [0.69101771 0.11472508 0.74122779 0.78419327 0.32211825]
 [0.49858385 0.64985531 0.25481509 0.988432   0.31861641]]
[[0.91219383 0.8511079  0.40759436 0.69236802 0.32397104]
 [0.75831775 0.67001515 0.34762066 0.73758716 0.25017712]
 [0.28305411 0.40916606 0.32531453 0.29084583 0.67766551]
 [0.6595949  0.         0.71706277 0.76623886 0.23737155]
 [0.439345   0.61248254 0.16033982 1.         0.23336353]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
import numpy as np

arr1=np.array([[2,3,4],[3,4,5],[4,5,6],[5,6,7],[6,7,8]])
arr2=np.array([[2,3],[3,4],[4,5]])

res=np.dot(arr1,arr2)

print(res)

[[29 38]
 [38 50]
 [47 62]
 [56 74]
 [65 86]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
import numpy as np

Z=np.array([1,2,3,4,5])

print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[   1    4   27  256 3125]
[ 1  2  4  8 16]
[False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[1. 2. 3. 4. 5.]


ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
import numpy as np

arr=np.array([[0.56,1.4,0.99],[1.2,0.7,1.5]])

round_arr=np.round(arr)

ceil_arr=np.ceil(arr)

print(round_arr)

print(ceil_arr)

[[1. 1. 1.]
 [1. 1. 2.]]
[[1. 2. 1.]
 [2. 1. 2.]]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
import numpy as np

arr1=np.array([[2,3,4],[3,4,5],[4,5,6],[5,6,7],[6,7,8]])
arr2=np.array([[1,0],[2,9],[3,10]])

comm=np.intersect1d(arr1,arr2)

print(comm)

[2 3]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
import numpy as np

Today=np.datetime64("today",'D')

Yesterday=Today-np.timedelta64(1,'D')

Tomorrow=Today+np.timedelta64(1,'D')

print(Today)
print(Yesterday)
print(Tomorrow)

2022-05-18
2022-05-17
2022-05-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
import numpy as np

month_dates=np.arange('2016-07','2016-08',dtype='datetime64[D]')

print(month_dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
import numpy as np

arr=np.random.rand(5,5)

a=np.floor(arr)
b=np.ceil(arr)
c=arr.astype(int)
d=np.trunc(arr)

print(arr-arr%1)
print(a)
print(b)
print(c)
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
import numpy as np

arr=np.linspace(0,4,25)

print(arr.reshape(5,5))





[[0.         0.16666667 0.33333333 0.5        0.66666667]
 [0.83333333 1.         1.16666667 1.33333333 1.5       ]
 [1.66666667 1.83333333 2.         2.16666667 2.33333333]
 [2.5        2.66666667 2.83333333 3.         3.16666667]
 [3.33333333 3.5        3.66666667 3.83333333 4.        ]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate(): 
    for x in range(10):
        yield x
        
Gen_Fun = np.fromiter(generate(), dtype=float, count=-1)
print (Gen_Fun)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
import numpy as np

res = np.linspace(0,1,12,endpoint=True)[1:-1]

print(res)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
import numpy as np

arr=np.random.random(10)

res=np.sort(arr)

print(res)

[0.07504625 0.08659493 0.17817097 0.20178439 0.56561889 0.63880583
 0.78862391 0.88044378 0.92133632 0.99166984]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
import numpy as np

arr1=np.array([1,2,3,4])

res1=np.add.reduce(arr1)

print(res1)

arr2=np.array([[1,2],[3,4]])

res2=np.add.reduce(arr2)

print(res2)




10
[4 6]


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
import numpy as np

arr1=np.random.rand(2,2,2)

arr2=np.random.rand(2,2,2)

res1=np.array_equal(arr1,arr2)

res2=np.allclose(arr1,arr2)

print(arr1)
print(arr2)
print(res1)
print(res2)



[[[0.96887829 0.93109601]
  [0.42953938 0.67898567]]

 [[0.01985076 0.92120438]
  [0.44847249 0.64622694]]]
[[[0.37963404 0.76069714]
  [0.03212465 0.13432638]]

 [[0.4850265  0.16057135]
  [0.01733658 0.71675158]]]
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr)

arr.flags.writeable=False

arr[0][1]=10





[[1 2 3]
 [4 5 6]
 [7 8 9]]


ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
import numpy as np

arr = np.random.random((10,2))
X,Y = arr[:,0], arr[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)

print(R)
print(T)

[0.78794426 0.51588147 0.48484505 0.86642936 1.3401486  0.15580961
 1.18583764 0.77397201 0.27581777 0.6773947 ]
[1.00072043 1.49441181 0.12401869 0.26681712 0.73759301 0.27643184
 0.64392878 0.92399965 1.12799605 0.90169224]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
import numpy as np

arr = np.random.random(10)
arr[arr.argmax()] = 0

print(arr)

[0.58107674 0.58373698 0.68735963 0.40965497 0.52022641 0.81798513
 0.05511427 0.         0.01496603 0.5095815 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
import numpy as np

arr = np.zeros((10,10), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(arr)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
import numpy as np

arr1=np.array([[64,4],[12,48]])
arr2=np.array([[7,49],[1,2]])

Cauchy_Mat=1/np.subtract.outer(arr1,arr2)

print(Cauchy_Mat)

[[[[ 0.01754386  0.06666667]
   [ 0.01587302  0.01612903]]

  [[-0.33333333 -0.02222222]
   [ 0.33333333  0.5       ]]]


 [[[ 0.2        -0.02702703]
   [ 0.09090909  0.1       ]]

  [[ 0.02439024 -1.        ]
   [ 0.0212766   0.02173913]]]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
import numpy as np

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
   
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
import numpy as np



#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
import numpy as np

arr = np.arange(100)
vec = np.random.uniform(0,100)
index = (np.abs(arr-vec)).argmin()
print(arr[index])

95


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
import numpy as np

Str_arr = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Str_arr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  import sys


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
import numpy as np

arr = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
Dis = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(Dis)


import scipy

import scipy.spatial

arr = np.random.random((10,2))
Dis = scipy.spatial.distance.cdist(arr,arr)
print(Dis)

[[0.         0.62280504 0.56621007 0.46941611 0.82005114 0.64381186
  0.87526272 0.44869991 0.09608739 0.88916727]
 [0.62280504 0.         0.32495079 0.49705807 0.33034451 0.25102105
  0.7657133  0.2617794  0.52876492 0.62296083]
 [0.56621007 0.32495079 0.         0.20816642 0.27971103 0.55407343
  0.45432591 0.14645818 0.49917177 0.36184263]
 [0.46941611 0.49705807 0.20816642 0.         0.47891696 0.68898118
  0.41284629 0.24263836 0.43392161 0.42792252]
 [0.82005114 0.33034451 0.27971103 0.47891696 0.         0.57390277
  0.54401352 0.37135174 0.74058703 0.34882022]
 [0.64381186 0.25102105 0.55407343 0.68898118 0.57390277 0.
  1.00606557 0.44819688 0.55013806 0.8731263 ]
 [0.87526272 0.7657133  0.45432591 0.41284629 0.54401352 1.00606557
  0.         0.58540913 0.84645426 0.2178617 ]
 [0.44869991 0.2617794  0.14645818 0.24263836 0.37135174 0.44819688
  0.58540913 0.         0.370958   0.50822448]
 [0.09608739 0.52876492 0.49917177 0.43392161 0.74058703 0.55013806
  0.84645426 0.37095

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
import numpy as np

arr = np.arange(10, dtype=np.int32)
arr = arr.astype(np.float32, copy=False)

print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
import numpy as np

arr = np.genfromtxt("missing.data", delimiter=",")

print(arr)

OSError: ignored

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
import numpy as np

arr = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(arr):
    print(index, value)

for index in np.ndindex(arr.shape):
    print(index, arr[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
import numpy as np

arr1=np.linspace(-4,4,10)
arr2=np.linspace(-4,4,10)

x,y=np.meshgrid(arr1,arr2)

distance=np.sqrt(x*x+y*y)

sigma=1
mu=0.000

G_Array=np.exp(-(distance-mu)**2/(2.0*(sigma**2)))

print(G_Array)

[[1.12535175e-07 2.65383134e-06 2.83995913e-05 1.37912809e-04
  3.03914109e-04 3.03914109e-04 1.37912809e-04 2.83995913e-05
  2.65383134e-06 1.12535175e-07]
 [2.65383134e-06 6.25832839e-05 6.69725939e-04 3.25229278e-03
  7.16697504e-03 7.16697504e-03 3.25229278e-03 6.69725939e-04
  6.25832839e-05 2.65383134e-06]
 [2.83995913e-05 6.69725939e-04 7.16697504e-03 3.48039396e-02
  7.66963443e-02 7.66963443e-02 3.48039396e-02 7.16697504e-03
  6.69725939e-04 2.83995913e-05]
 [1.37912809e-04 3.25229278e-03 3.48039396e-02 1.69013315e-01
  3.72449314e-01 3.72449314e-01 1.69013315e-01 3.48039396e-02
  3.25229278e-03 1.37912809e-04]
 [3.03914109e-04 7.16697504e-03 7.66963443e-02 3.72449314e-01
  8.20754808e-01 8.20754808e-01 3.72449314e-01 7.66963443e-02
  7.16697504e-03 3.03914109e-04]
 [3.03914109e-04 7.16697504e-03 7.66963443e-02 3.72449314e-01
  8.20754808e-01 8.20754808e-01 3.72449314e-01 7.66963443e-02
  7.16697504e-03 3.03914109e-04]
 [1.37912809e-04 3.25229278e-03 3.48039396e-02 1.69013315e

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5])

arr=np.put(arr,[0,2],[-64,64])

print(arr)



None


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
import numpy as np

arr = np.random.rand(5, 10)

new_arr = arr - arr.mean(axis=1, keepdims=True)

print(new_arr)




[[-0.1742799  -0.03638803 -0.12827853 -0.23922312  0.1498886  -0.15905136
   0.25902323 -0.20530699  0.05299606  0.48062004]
 [ 0.14287864  0.17120958  0.2417514   0.02354739 -0.0573308  -0.14912341
   0.26385427  0.04927796 -0.18787721 -0.49818783]
 [-0.16691114 -0.11066448 -0.42400404  0.20728318 -0.42427147 -0.28339814
   0.28014763  0.51432677  0.04247694  0.36501474]
 [-0.10432315  0.031122   -0.01122136 -0.0107306  -0.2417201   0.28555233
   0.304205   -0.00063346  0.19778649 -0.45003715]
 [ 0.11013235 -0.42734537 -0.07003127  0.46951018 -0.26158413 -0.04435967
  -0.06294001  0.31297108  0.08620191 -0.11255506]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
import numpy as np

arr = np.random.randint(0,10,(3,3))

print(arr)
print(arr[arr[:,1].argsort()])

[[4 1 4]
 [4 7 9]
 [0 0 6]]
[[0 0 6]
 [4 1 4]
 [4 7 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
import numpy as np

arr = np.random.randint(0,3,(3,10))

res=(~arr.any(axis=0)).any()

print(res)

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
import numpy as np

arr = np.random.uniform(0,1,10)
val = 0.5
res = arr.flat[np.abs(arr-val).argmin()]

print(res)

0.5012076838523128


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
import numpy as np

arr = np.ones(10)
ran_arr = np.random.randint(0,len(Z),20)
arr += np.bincount(ran_arr, minlength=len(arr))

print(arr)

[3. 3. 2. 2. 2. 5. 4. 2. 4. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
import numpy as np

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)

print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
import numpy as np

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
res=np.unique(I)

print(res)

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
import numpy as np

arr = np.random.randint(0,10,(3,4,3,4))
sum = arr.reshape(arr.shape[:-2] + (-1,)).sum(axis=-1)

print(sum)

[[49 53 62 51]
 [67 59 66 37]
 [71 53 54 75]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
import numpy as np

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts

print(D_means)

[0.41831371 0.52016608 0.47406357 0.50238367 0.55526441 0.54296652
 0.37464276 0.48269032 0.55710327 0.56733893]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
import numpy as np

arr1=np.array([[2,3,4],[3,4,5]])
arr2=np.array([[4,5],[6,7],[8,9]])

dot_P=np.dot(arr1,arr2)

res=np.diag(dot_P)

print(dot_P)
print(res)

[[58 67]
 [76 88]]
[58 88]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
import numpy as np

vec = np.array([1,2,3,4,5])

ze = 3
new_vec = np.zeros(len(vec) + (len(vec)-1)*(ze))
new_vec[::ze+1] = vec

print(new_vec)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
import numpy as np

arr1 = np.ones((5,5,3))
arr2 = 2*np.ones((5,5))
res=arr1* arr2[:,:,None]

print(res)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
import numpy as np

arr = np.arange(16).reshape(4,4)
print(arr)

arr[[0,1]] = arr[[1,0]]
print(arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
import numpy as np

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
res = np.unique(G)

print(res)

[( 9, 68) ( 9, 80) ( 9, 86) ( 9, 98) (10, 40) (10, 48) (10, 54) (10, 88)
 (11, 54) (11, 89) (23, 82) (23, 88) (26, 68) (26, 97) (39, 42) (39, 75)
 (39, 78) (39, 98) (40, 48) (42, 75) (54, 88) (54, 89) (65, 76) (65, 92)
 (68, 97) (68, 98) (76, 92) (78, 98) (80, 86) (82, 88)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
import numpy as np

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)

print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
import numpy as np

def average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
arr = np.arange(20)

print(average(arr, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
import numpy as np

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

arr = rolling(np.arange(10), 3)
print(arr)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
import numpy as np

arr1 = np.random.randint(0,2,100)
print ('original_Array: ')
print (arr1)

print('Negating a boolean: ')
print(np.logical_not(arr1, out=arr1))


arr2= np.random.uniform(-1.0,1.0,10)
print ('original_Array: ')
print (arr2)
print ('Change the sign of float inplace: ')
print(np.negative(arr2, out=arr2))

original_Array: 
[1 1 1 0 0 1 1 0 0 1 1 1 0 1 0 0 1 1 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1
 0 0 0 0 1 0 1 1 1 1 0 1 0 1 1 0 0 1 0 1 0 0 0 1 0 1 1 0 0 1 0 0 0 0 1 0 1
 0 1 0 1 0 0 0 1 0 1 1 1 1 1 1 0 1 1 0 0 0 1 1 0 0 1]
Negating a boolean: 
[0 0 0 1 1 0 0 1 1 0 0 0 1 0 1 1 0 0 0 1 0 1 0 1 1 1 1 1 0 1 0 1 1 0 0 0 0
 1 1 1 1 0 1 0 0 0 0 1 0 1 0 0 1 1 0 1 0 1 1 1 0 1 0 0 1 1 0 1 1 1 1 0 1 0
 1 0 1 0 1 1 1 0 1 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 0]
original_Array: 
[-0.17799887 -0.09570124 -0.78238411  0.29455838 -0.55592153  0.78741475
 -0.55333298  0.54540333  0.7316355  -0.18312378]
Change the sign of float inplace: 
[ 0.17799887  0.09570124  0.78238411 -0.29455838  0.55592153 -0.78741475
  0.55333298 -0.54540333 -0.7316355   0.18312378]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
import numpy as np

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
res=distance(P0, P1, p)

print(res)

[9.93624507 8.4292645  8.59353498 7.94721071 2.64010074 9.60557488
 3.20609979 4.81655155 6.93225885 2.02108094]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
import numpy as np

P0 = np.random.uniform(-10, 10, (5,2))
P1 = np.random.uniform(-10,10,(5,2))
p = np.random.uniform(-10, 10, (5,2))
res=np.array([distance(P0,P1,p_i) for p_i in p])

print(res)


[[6.02765523 4.79712295 4.17058914 2.4468664  9.17795343]
 [2.4564555  3.24725986 7.12010098 1.06962346 3.63416266]
 [6.06921643 5.89505836 0.09313127 2.09221043 5.224782  ]
 [5.70696652 6.86407252 5.23594498 7.89179995 0.052793  ]
 [4.4012216  3.59306635 3.37886088 0.31752134 6.8439261 ]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
import numpy as np

arr = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=arr.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(arr.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = arr[z]

print(arr)
print(R)

[[6 7 5 0 5 9 2 4 9 6]
 [2 8 3 8 7 0 2 0 5 9]
 [3 2 4 0 1 2 0 2 9 8]
 [6 0 3 3 3 8 5 7 0 4]
 [8 9 4 0 8 9 4 4 1 1]
 [2 3 9 0 2 8 8 7 3 5]
 [0 1 9 8 0 0 9 7 1 2]
 [8 8 7 8 6 0 2 6 5 6]
 [2 4 4 0 8 2 1 7 9 9]
 [6 8 4 7 8 9 4 0 0 3]]
[[0 0 0 0 0]
 [0 6 7 5 0]
 [0 2 8 3 8]
 [0 3 2 4 0]
 [0 6 0 3 3]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
import numpy as np

arr = np.arange(1,15,dtype=int)

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

R = rolling(arr, 4)
print ('Original_Arr: ')
print (arr)

print ('After Strides: ')
print(R)

Original_Arr: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After Strides: 
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
import numpy as np

arr=np.array([[2,3,4],[89,64,52]])

res=np.linalg.matrix_rank(arr)

print(res)

2


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
import numpy as np

arr=np.array([1,9,8,7,6,7,4,4,7,1,9])

count=np.bincount(arr)

res=np.argmax(count)

print(count)

print(res)

[0 2 0 0 2 0 1 3 1 2]
7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
import numpy as np

arr = np.random.randint(0,5,(6,6))
n = 3
i = 1 + (arr.shape[0]-3)
j = 1 + (arr.shape[1]-3)
res = np.lib.stride_tricks.as_strided(arr, shape=(i, j, n, n), strides=arr.strides + arr.strides)

print(res)

[[[[2 0 2]
   [2 4 1]
   [3 3 3]]

  [[0 2 0]
   [4 1 3]
   [3 3 1]]

  [[2 0 3]
   [1 3 2]
   [3 1 4]]

  [[0 3 4]
   [3 2 1]
   [1 4 4]]]


 [[[2 4 1]
   [3 3 3]
   [4 0 4]]

  [[4 1 3]
   [3 3 1]
   [0 4 2]]

  [[1 3 2]
   [3 1 4]
   [4 2 0]]

  [[3 2 1]
   [1 4 4]
   [2 0 3]]]


 [[[3 3 3]
   [4 0 4]
   [3 0 1]]

  [[3 3 1]
   [0 4 2]
   [0 1 3]]

  [[3 1 4]
   [4 2 0]
   [1 3 1]]

  [[1 4 4]
   [2 0 3]
   [3 1 1]]]


 [[[4 0 4]
   [3 0 1]
   [3 3 2]]

  [[0 4 2]
   [0 1 3]
   [3 2 3]]

  [[4 2 0]
   [1 3 1]
   [2 3 3]]

  [[2 0 3]
   [3 1 1]
   [3 3 4]]]]


#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
import numpy as np

p, n = 10, 20
arr1 = np.ones((p,n,n))
arr2 = np.ones((p,n,1))
res = np.tensordot(arr1, arr2, axes=[[0, 2], [0, 1]])

print(res)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
import numpy as np

arr = np.ones((16,16))
size = 4
res = np.add.reduceat(np.add.reduceat(arr, np.arange(0, arr.shape[0], size), axis=0),
                                       np.arange(0, arr.shape[1], size), axis=1)
print ('input array')
print (arr)

print ('block sum')
print (res)

input array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
block sum
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
import numpy as np

def iterate(arr):
   
    N = (arr[0:-2,0:-2] + arr[0:-2,1:-1] + arr[0:-2,2:] +
         arr[1:-1,0:-2]                + arr[1:-1,2:] +
         arr[2:  ,0:-2] + arr[2:  ,1:-1] + arr[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (arr[1:-1,1:-1]==1)
    arr[...] = 0
    arr[1:-1,1:-1][birth | survive] = 1
    return arr

arr = np.random.randint(0,2,(50,50))
for i in range(100): arr = iterate(arr)

print(arr)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
import numpy as np

arr = np.arange(10000)
np.random.shuffle(arr)
n = 5

res=arr[np.argpartition(-arr,n)[:n]]

print(res)



[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
import numpy as np

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

res=cartesian(([1, 2, 3], [4, 5], [6, 7]))
print (res)

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
import numpy as np

arr = np.array([("Bhavana",23,"Infosys"),
                 ("Navya", 22, "Tcs")])
print(arr1)

rec_arr = np.core.records.fromarrays(arr.T,
                              names='col1, col2',
                              formats = 'S80,i8,S80')
print(rec_arr)
             

[['Bhavana' '23' 'Infosys']
 ['Navya' '22' 'Tcs']]
[(b'Bhavana', 23, b'Infosys') (b'Navya', 22, b'Tcs')]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
import numpy as np

x = np.random.randint(0,10,(50,50))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)




The slowest run took 10.36 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 6.94 µs per loop
The slowest run took 9.11 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 4.56 µs per loop


ValueError: ignored

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
import numpy as np

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

arr = (A[..., np.newaxis, np.newaxis] == B)
rows = (arr.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]

print(rows)

[0 1 3 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
import numpy as np

arr = np.random.randint(0,5,(10,3))
arr_form = np.logical_and.reduce(arr[:,1:] == arr[:,:-1], axis=1)
res = arr[~arr_form]

print(arr)
print(res)

[[0 0 1]
 [3 4 2]
 [1 0 2]
 [0 4 0]
 [4 4 0]
 [4 2 4]
 [0 3 3]
 [3 3 4]
 [4 2 2]
 [3 1 3]]
[[0 0 1]
 [3 4 2]
 [1 0 2]
 [0 4 0]
 [4 4 0]
 [4 2 4]
 [0 3 3]
 [3 3 4]
 [4 2 2]
 [3 1 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
import numpy as np

int_arr = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
bin_arr = ((int_arr.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
res1=bin_arr[:,::-1]
print(res1)

Int = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
res2=np.unpackbits(I[:, np.newaxis], axis=1)
print(res2)





[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[[[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  ...

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 1 0]
   [1 0 1]
   [1 0 0]
   ...
   [1 0 0]
   [0 1 0]
   [0 0 1]]]


 [[[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  ...

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
import numpy as np

arr = np.random.randint(0,2,(6,3))
arr_mid = np.ascontiguousarray(arr).view(np.dtype((np.void, arr.dtype.itemsize * arr.shape[1])))
_, idx = np.unique(arr_mid, return_index=True)
res = arr[idx]

print(res)

[[0 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
import numpy as np


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
import numpy as numpy

arr = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*arr*np.cos(arr)
y = a*arr*np.sin(arr)

Seg_len = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(Seg_len)                
reg_spaced_path = np.linspace(0, r.max(), 200) 
x_int = np.interp(reg_spaced_path, r, x)       
y_int = np.interp(reg_spaced_path, r, y)

print(x_int)
print(y_int)

[ 0.00000000e+00 -3.73131229e-01 -2.59817608e+00 -3.26212050e+00
 -2.18442687e+00 -2.98929946e-02  2.42923642e+00  4.54913599e+00
  5.92318348e+00  6.35117933e+00  5.82369277e+00  4.46259540e+00
  2.47320794e+00  1.09577220e-01 -2.36575300e+00 -4.71261671e+00
 -6.72701769e+00 -8.25541575e+00 -9.18486120e+00 -9.46381505e+00
 -9.11085788e+00 -8.12875279e+00 -6.63306046e+00 -4.69271059e+00
 -2.44736165e+00 -2.05444585e-02  2.46101146e+00  4.86841760e+00
  7.08937968e+00  9.02539126e+00  1.05948609e+01  1.17357250e+01
  1.24068974e+01  1.25885805e+01  1.22815267e+01  1.15053927e+01
  1.02963689e+01  8.70429550e+00  6.78948686e+00  4.61716636e+00
  2.25853448e+00 -1.98731680e-01 -2.68040566e+00 -5.11543300e+00
 -7.41973991e+00 -9.53891040e+00 -1.14237629e+01 -1.29919305e+01
 -1.42355069e+01 -1.51243232e+01 -1.56061571e+01 -1.57219415e+01
 -1.54217066e+01 -1.47579136e+01 -1.37255236e+01 -1.23634834e+01
 -1.07024632e+01 -8.78327367e+00 -6.65029558e+00 -4.35514246e+00
 -1.94290275e+00  5.28038

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)